codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests/_data/*"
  - "tests/_output/*"
  - "modules/AOS_PDF_Templates/PDF_Lib/utils/*"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no