set DATABASE_DRIVER=MYSQL
set DATABASE_NAME=automated_tests
set DATABASE_HOST=localhost
set DATABASE_USER=automated_tests
set DATABASE_PASSWORD=automated_tests
set INSTANCE_URL=http://path/to/instance
set INSTANCE_ADMIN_USER=admin
set INSTANCE_ADMIN_PASSWORD=admin
set INSTANCE_CLIENT_ID=suitecrm_client
set INSTANCE_CLIENT_SECRET=secret
.\vendor\bin\codecept  %*
